### PR TITLE
Introduce keyboard shortcut

### PR DESCRIPTION
**Pull request by mlalkaka**
Register a keyboard shortcut (keybinding) to toggle desaturation. This
keybinding is stored using GSettings, just like GNOME keybindings. As
such, it can also be overridden by users to suit their needs, or
disabled entirely.

The keybinding is registered with the window manager, so the extension
doesn't have to do any interpretation of modifier keys, etc. GNOME takes
care of all of that!

The one drawback of this change is that it requires additional steps
during installation in order to compile the GSettings schema and make
~/.local/share a path that is searched for compiled GSettings schemas.
I'm not sure if there's a way around that; let me know if you think
there's a better way to do this.

Also, if you have a suggestion for a better default keyboard shortcut, let me know. Right now, I arbitrarily chose `<Super>`+`e`.

### CODE REVIEW

**Comment by laerne** [comment]
Nice, I always wanted a keyboard shortcut, but I stop developping the add when I could not find JS documentation anymore.  But I could find some again : https://gjs-docs.gnome.org/ Yeah :)

When I look at other extensions, like [here](https://github.com/mkrajnak/shutdown-timer-gnome-shell-extension/blob/master/convenience.js) and [here](https://github.com/mlutfy/hidetopbar/blob/master/convenience.js) : they do not hardcode the schema, but rather create one dynamically using GioSSS, which avoids to have to manually install the schema.  I believe I prefer that.

**Comment by mlalkaka** [comment]
Thanks for the pointers for GioSSS and the examples! That will be much better, especially so that people can seamlessly install it from the GNOME Extensions store/website. I'll give it a shot :+1:

**Comment by mlalkaka** [comment]
Hi @laerne, I've updated the pull request with a better implementation that doesn't require special installation instructions. I've also updated the README to include instructions on how to change the keybinding, given that there isn't a preferences UI. Do you mind taking a look?

**Comment by laerne** [comment]
Okay, sorry.  I didn't have time then (since I don't know how the schema mechanism work, it's quite a time-expensive task for me to review) and I forget since.

I'm not too found of versioning the compiled schema, but quite fine by me for a first shot.
It would also be nice of being able to edit the shortcut with dconf editor the first time.  I will merge anyway, but be glad if there was improvement on this.

**Comment by mlalkaka** [comment]
Thanks for merging, and no worries about the delay! I actually hadn't had a chance to return to work on it for quite a while as well.

I decided to version the compiled schema because that's what other GNOME extensions are doing, and because it is a very small binary blob. I believe the reason this is the only way to make the extension installable with just a copy command, which is required for installations via the GNOME Extensions website.

Yes, I'd like to implement a settings UI where settings like these could be changed as well. I just haven't had a chance to do that yet. I figured this was better than nothing.

Would you be willing to publish an updated version to the GNOME Extensions website? I know some people who would like the updated version with the keyboard shortcut, and the easiest way for them to get it is through the GNOME Software Center and/or the Extensions website. (Also, I'd be happy to become a Collaborator on this project and help with these kind of things, to save you time.)

**Pull request merged**
